const DB_KEY = 'sentry-tsrp-v1';
const seed = { owner: { name:'Director', username:'director', password:'3383', role:'Director' }, members:[
 {id:1,name:'Director',rank:'Director',code:'TSRP-DIR-01',status:'On Duty',lastLogin:'Never'}],
 codes:[], escorts:[], schedules:[], logs:[] };
let db = JSON.parse(localStorage.getItem(DB_KEY) || 'null') || seed;
db.accounts ||= [{username:'director',password:'3383',name:'Director Harper',role:'Director'}];
// Upgrade existing browser data from the original prototype password.
if (db.owner?.username === 'director' && db.owner.password === 'sentry') {
  db.owner.password = '3383';
  const directorAccount = db.accounts.find(account => account.username === 'director');
  if (directorAccount?.password === 'sentry') directorAccount.password = '3383';
  localStorage.setItem(DB_KEY, JSON.stringify(db));
}
// Remove the clearly labeled sample records from earlier demo versions without
// touching members, requests, or codes that command has actually created.
const sampleMembers = new Set(['A. Mitchell', 'J. Carter']);
const hadSampleData = db.members?.some(member => sampleMembers.has(member.name)) || db.owner?.name === 'Director Harper';
if (hadSampleData) {
  db.members = db.members.filter(member => !sampleMembers.has(member.name));
  db.codes = db.codes.filter(invite => !['TSRP-RECRUIT-91', 'TSRP-TEMP-44'].includes(invite.code));
  db.escorts = db.escorts.filter(request => !['Governor Williams', 'Mayor Collins'].includes(request.principal));
  db.schedules = db.schedules.filter(detail => !['Capitol Detail', 'Command Briefing'].includes(detail.title));
  if (db.owner.name === 'Director Harper') {
    db.owner.name = 'Director';
    const directorAccount = db.accounts.find(account => account.username === 'director');
    if (directorAccount) directorAccount.name = 'Director';
    const directorMember = db.members.find(member => member.code === 'TSRP-DIR-01');
    if (directorMember) directorMember.name = 'Director';
  }
  localStorage.setItem(DB_KEY, JSON.stringify(db));
}
let session = JSON.parse(sessionStorage.getItem('sentry-user') || 'null'); let page='Dashboard';
const save=()=>localStorage.setItem(DB_KEY,JSON.stringify(db)); const $=s=>document.querySelector(s);
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function id(){return Date.now()+Math.floor(Math.random()*1000)} function code(){return 'TSRP-'+Math.random().toString(36).slice(2,7).toUpperCase()+'-'+Math.floor(10+Math.random()*89)}
function badge(status){let c=status==='On Duty'||status==='Assigned'||status==='Approved'?'green':status==='Pending'||status==='Temporary'?'gold':status==='Denied'||status==='Revoked'?'red':'';return `<span class="badge ${c}">${esc(status)}</span>`}
function nav(){return ['Dashboard','Members','Access Codes','Schedule','Escort Requests','Operations'].map(x=>`<button class="${page===x?'active':''}" data-page="${x}"><span class="icon">${({Dashboard:'▦',Members:'♙','Access Codes':'⌘',Schedule:'□','Escort Requests':'◇',Operations:'◉'})[x]}</span>${x}</button>`).join('')}
function layout(body){return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="crest">S</div><div><b>SENTRY</b><small>TSRP SECRET SERVICE</small></div></div><nav class="nav">${nav()}</nav><div class="side-bottom"><b><span class="status-dot"></span>System Secure</b>TSRP Operations Network</div></aside><main class="content"><div class="topbar"><div><div class="eyebrow">Tennessee State Roleplay</div><h1>${page}</h1></div><div class="user"><div class="avatar">${session.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span>${esc(session.name)}<small style="display:block;color:#9ba8bb">${esc(session.role)}</small></span></div></div>${body}</main></div>`}
function dashboard(){let pending=db.escorts.filter(x=>x.status==='Pending').length;return `<div class="grid four"><div class="card"><div class="muted">Active Agents</div><div class="stat">${db.members.filter(x=>x.status==='On Duty').length}</div><div class="trend">● On duty now</div></div><div class="card"><div class="muted">Escort Requests</div><div class="stat">${db.escorts.length}</div><div class="trend ${pending?'warn':''}">${pending} awaiting review</div></div><div class="card"><div class="muted">Open Access Codes</div><div class="stat">${db.codes.filter(x=>!x.used).length}</div><div class="trend">Invite-ready</div></div><div class="card"><div class="muted">This Week's Details</div><div class="stat">${db.schedules.length}</div><div class="trend">Next: ${db.schedules[0]?.title||'None'}</div></div></div><div class="grid two"><section><div class="section-head"><h2>Upcoming Schedule</h2><button class="btn small" data-page="Schedule">View schedule</button></div><div class="card list">${db.schedules.slice(0,4).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-sub">${esc(x.date)} · ${esc(x.time)} · ${esc(x.agents)}</div></div><span class="badge">DETAIL</span></div>`).join('')||'<div class="empty">No shifts scheduled.</div>'}</div></section><section><div class="section-head"><h2>Escort Requests</h2><button class="btn small" data-page="Escort Requests">Manage</button></div><div class="card list">${db.escorts.slice(0,4).map(x=>`<div class="row"><div><div class="row-title">${esc(x.principal)}</div><div class="row-sub">${esc(x.date)} · ${esc(x.location)}</div></div>${badge(x.status)}</div>`).join('')||'<div class="empty">No escort requests.</div>'}</div></section></div>`}
function members(){return `<div class="section-head"><h2>Agent Directory</h2><button class="btn" data-modal="member">+ Add member</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Name</th><th>Rank</th><th>Assigned Code</th><th>Status</th><th>Last Login</th></tr></thead><tbody>${db.members.map(m=>`<tr><td class="name">${esc(m.name)}</td><td>${esc(m.rank)}</td><td><span class="code">${esc(m.code)}</span></td><td>${badge(m.status)}</td><td class="muted">${esc(m.lastLogin)}</td></tr>`).join('')}</tbody></table></div><p class="muted">Login records are kept on this device. When Sentry is hosted, they will be available to all authorized administrators.</p>`}
function codes(){return `<div class="section-head"><h2>Access Code Management</h2><button class="btn" data-modal="code">+ Create code</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Access Code</th><th>Type</th><th>Role on Redeem</th><th>Assigned To</th><th>Status</th><th></th></tr></thead><tbody>${db.codes.map(c=>`<tr><td><span class="code">${esc(c.code)}</span></td><td>${c.type==='Permanent'?badge('Permanent'):badge('Temporary')}</td><td>${esc(c.rank)}</td><td>${esc(c.assigned)}</td><td>${c.used?badge('Redeemed'):badge('Available')}</td><td><button class="btn small danger" data-delete-code="${c.id}">Revoke</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No invitation codes have been created.</td></tr>'}</tbody></table></div><p class="muted">Permanent codes remain available until you revoke them. One-time codes are automatically closed after redemption.</p>`}
function schedule(){return `<div class="section-head"><h2>Detail Schedule</h2><button class="btn" data-modal="schedule">+ Schedule detail</button></div><div class="grid two"><div class="card list">${db.schedules.map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-sub">${esc(x.date)} at ${esc(x.time)} · ${esc(x.agents)}</div></div><span class="badge">SCHEDULED</span></div>`).join('')||'<div class="empty">No details scheduled yet.</div>'}</div><div class="card"><div class="card-title">July 2026</div><div class="calendar">${Array.from({length:31},(_,i)=>{let d=i+1;let e=db.schedules.find(s=>s.date.includes(' '+d));return `<div class="day"><strong>${d}</strong>${e?`<div class="event">${esc(e.title)}</div>`:''}</div>`}).join('')}</div></div></div>`}
function escorts(){return `<div class="section-head"><h2>Protection Escort Requests</h2><button class="btn" data-modal="escort">+ New request</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Principal</th><th>Date & Time</th><th>Location</th><th>Agents Assigned</th><th>Status</th><th></th></tr></thead><tbody>${db.escorts.map(e=>`<tr><td><div class="name">${esc(e.principal)}</div><div class="muted">Requested by ${esc(e.requester)}</div></td><td>${esc(e.date)}</td><td>${esc(e.location)}</td><td>${esc(e.agents)}</td><td>${badge(e.status)}</td><td>${e.status==='Pending'?`<button class="btn small" data-approve="${e.id}">Approve</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No requests have been submitted.</td></tr>'}</tbody></table></div>`}
function operations(){return `<div class="section-head"><h2>Operations Board</h2><button class="btn" data-modal="operation">+ Log operation</button></div><div class="card list">${db.logs.length?db.logs.map(l=>`<div class="row"><div><div class="row-title">${esc(l.title)}</div><div class="row-sub">${esc(l.detail)} · Logged ${esc(l.time)}</div></div>${badge(l.status)}</div>`).join(''):'<div class="empty">No operations logged. Use this board for incidents, protective intelligence, or after-action notes.</div>'}</div>`}
function view(){let content={Dashboard:dashboard,Members:members,'Access Codes':codes,Schedule:schedule,'Escort Requests':escorts,Operations:operations}[page](); $('#app').innerHTML=layout(content); bind();}
function modal(type){let forms={member:['Add Member',`<div class="form-grid"><div class="field"><label>Full display name</label><input name="name" required placeholder="e.g. A. Mitchell"></div><div class="field"><label>Rank</label><input name="rank" required placeholder="Special Agent"></div><div class="field"><label>Permanent code</label><input name="code" value="${code()}" required></div><div class="field"><label>Duty status</label><select name="status"><option>On Duty</option><option>Off Duty</option></select></div></div>`],code:['Create Access Code',`<div class="form-grid"><div class="field"><label>Code type</label><select name="type"><option>Permanent</option><option>One-time</option></select></div><div class="field"><label>Role on redeem</label><input name="rank" required value="Trainee"></div><div class="field full"><label>Access code</label><input name="code" required value="${code()}"></div></div>`],schedule:['Schedule Detail',`<div class="form-grid"><div class="field"><label>Detail name</label><input name="title" required></div><div class="field"><label>Date</label><input name="date" required placeholder="Jul 31"></div><div class="field"><label>Start time</label><input name="time" required placeholder="7:00 PM"></div><div class="field"><label>Assigned agents</label><input name="agents" required placeholder="Names, separated by commas"></div></div>`],escort:['New Protection Escort Request',`<div class="form-grid"><div class="field"><label>Principal / protected person</label><input name="principal" required></div><div class="field"><label>Requester</label><input name="requester" required></div><div class="field"><label>Date & time</label><input name="date" required placeholder="Jul 31, 2026 · 7:00 PM"></div><div class="field"><label>Location</label><input name="location" required></div><div class="field full"><label>Notes / mission details</label><textarea name="notes"></textarea></div></div>`],operation:['Log Operation',`<div class="form-grid"><div class="field"><label>Operation title</label><input name="title" required></div><div class="field"><label>Status</label><select name="status"><option>Active</option><option>Complete</option><option>Pending</option></select></div><div class="field full"><label>Notes</label><textarea name="detail" required></textarea></div></div>`]}[type]; $('#app').insertAdjacentHTML('beforeend',`<div class="modal-bg"><form class="modal" id="modal-form" data-type="${type}"><h2>${forms[0]}</h2><p class="muted">Sentry Operations Network</p>${forms[1]}<div class="actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn">Save</button></div></form></div>`); $('#modal-form').addEventListener('submit',submitModal); $('[data-close]').onclick=()=>$('.modal-bg').remove();}
function submitModal(e){e.preventDefault();let f=Object.fromEntries(new FormData(e.target)), type=e.target.dataset.type; if(type==='member') db.members.push({id:id(),...f,lastLogin:'Never'});if(type==='code')db.codes.push({id:id(),...f,assigned:'Unclaimed',used:false});if(type==='schedule')db.schedules.push({id:id(),...f});if(type==='escort')db.escorts.push({id:id(),...f,status:'Pending',agents:'—'});if(type==='operation')db.logs.unshift({id:id(),...f,time:new Date().toLocaleString()});save();$('.modal-bg').remove();view();}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;view()});document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>modal(b.dataset.modal));document.querySelectorAll('[data-delete-code]').forEach(b=>b.onclick=()=>{db.codes=db.codes.filter(x=>x.id!=b.dataset.deleteCode);save();view()});document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{let x=db.escorts.find(x=>x.id==b.dataset.approve);x.status='Approved';save();view()});}
function login(){ $('#app').innerHTML=`<main class="login"><section class="login-card" id="login-box"><div class="crest">S</div><h1>SENTRY</h1><p>TSRP Secret Service Operations Network</p><form id="login"><div class="field"><label>Username</label><input name="username" autocomplete="username" placeholder="director" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn">Secure Sign In</button></form><div class="notice" id="notice"></div><button class="btn secondary" style="width:100%;margin-top:10px" id="activate">Activate an access code</button><p class="hint">First-run director account:<br><b>director</b> / <b>sentry</b></p></section></main>`;$('#login').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),account=db.accounts.find(a=>a.username.toLowerCase()===f.username.toLowerCase()&&a.password===f.password);if(account){session={name:account.name,role:account.role};let member=db.members.find(m=>m.name===account.name);if(member)member.lastLogin='Just now';save();sessionStorage.setItem('sentry-user',JSON.stringify(session));view()}else $('#notice').textContent='Incorrect username or password.'};$('#activate').onclick=activateForm;}
function activateForm(){ $('#login-box').innerHTML=`<div class="crest">S</div><h1>ACTIVATE</h1><p>Enter the Sentry access code provided by command.</p><form id="activate-form"><div class="field"><label>Access code</label><input name="code" placeholder="TSRP-XXXXX-00" required style="text-transform:uppercase"></div><div class="field"><label>Your display name</label><input name="name" placeholder="Roblox / Discord name" required></div><div class="field"><label>Create username</label><input name="username" required></div><div class="field"><label>Create password</label><input name="password" type="password" minlength="4" required></div><button class="btn">Activate Account</button></form><div class="notice" id="notice"></div><button class="btn secondary" style="width:100%;margin-top:10px" id="back">Back to sign in</button>`;$('#back').onclick=login;$('#activate-form').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),input=f.code.trim().toUpperCase(),invite=db.codes.find(c=>c.code===input),member=db.members.find(m=>m.code===input);let valid=invite&&(!invite.used||invite.type==='Permanent') || member;if(!valid){$('#notice').textContent='That code is invalid or has already been redeemed.';return}if(db.accounts.some(a=>a.username.toLowerCase()===f.username.toLowerCase())){$('#notice').textContent='That username is already taken.';return}let role=member?member.rank:invite.rank;db.accounts.push({username:f.username,password:f.password,name:f.name,role});if(member){member.name=f.name;member.lastLogin='Just now'}else {db.members.push({id:id(),name:f.name,rank:role,code:invite.code,status:'Off Duty',lastLogin:'Just now'});invite.assigned=f.name;if(invite.type==='One-time')invite.used=true}save();session={name:f.name,role};sessionStorage.setItem('sentry-user',JSON.stringify(session));view()};}
session?view():login();
